# we ignore all octokit packages because we dont have any incoming/user driven requests to it and only
# use to create and upload releases
[[PackageOverrides]]
name = "octokit"
ignore = true

[[PackageOverrides]]
name = "@octokit/endpoint"
ignore = true

[[PackageOverrides]]
name = "@octokit/app"
ignore = true

[[PackageOverrides]]
name = "@octokit/core"
ignore = true

[[PackageOverrides]]
name = "@octokit/oauth-app"
ignore = true

[[PackageOverrides]]
name = "@octokit/plugin-paginate-graphql"
ignore = true

[[PackageOverrides]]
name = "@octokit/plugin-paginate-rest"
ignore = true

[[PackageOverrides]]
name = "@octokit/plugin-rest-endpoint-methods"
ignore = true

[[PackageOverrides]]
name = "@octokit/plugin-retry"
ignore = true

[[PackageOverrides]]
name = "@octokit/plugin-throttling"
ignore = true

[[PackageOverrides]]
name = "@octokit/request-error"
ignore = true

[[PackageOverrides]]
name = "@octokit/request"
ignore = true

[[PackageOverrides]]
name = "@octokit/types"
ignore = true

[[IgnoredVulns]]
id = "GHSA-67mh-4wv8-2f99"
reason = "We do not use the esbuild development server"

[[IgnoredVulns]]
id = "GHSA-67mh-4wv8-2f99"
reason = "We do not use the esbuild development server"

[[IgnoredVulns]]
id = "GHSA-jr5f-v2jv-69x6"
reason = "We only use axios in examples"

[[IgnoredVulns]]
id = "GHSA-3xgq-45jj-v275"
reason = "cross-spawn is used in development/testing - it's not used in the final production build"

