services:
    gha-runner:
        build:
            context: .
        environment:
            REPO_URL: ${REPO_URL}
            RUNNER_NAME: ${RUNNER_NAME}
            RUNNER_TOKEN: ${RUNNER_TOKEN}
            RUNNER_WORKDIR: /tmp/runner/work
            CONFIGURED_ACTIONS_RUNNER_FILES_DIR: /runner/data
            RUNNER_SCOPE: 'repo'
            LABELS: ${LABELS}
            ACTIONS_RESULTS_URL: http://gha-cache:3000/
            DISABLE_AUTOMATIC_DEREGISTRATION: 'true'
            EPHEMERAL: 'true'
        restart: unless-stopped
        security_opt:
            # needed on SELinux systems to allow docker container to manage other docker containers
            - label:disable
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - 'runner-data:/runner/data' # required for persistence
            - '/tmp/runner:/tmp/runner'
            # note: a quirk of docker-in-docker is that this path
            # needs to be the same path on host and inside the container,
            # docker mgmt cmds run outside of docker but expect the paths from within

    gha-cache:
        image: ghcr.io/falcondev-oss/github-actions-cache-server:latest
        ports:
            - '3000:3000'
        environment:
            API_BASE_URL: http://gha-cache:3000
        volumes:
            - cache-data:/app/.data

volumes:
    runner-data:
    cache-data:
